remote_theme: thuhcsi/slate
title: A CHARACTER-LEVEL SPAN-BASED MODEL FOR MANDARIN PROSODIC STRUCTURE PREDICTION
description: submitted to ICASSP 2022.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
